#if !defined(CONFIG_HPP)
#define CONFIG_HPP

#define C_TABLE_HEIGHT 1.25f

#define C_REAL_AQUARIUM_HEIGHT 94.5f
#define C_AQUARIUM_HEIGHT 3.0f
#define C_AQUARIUM_SCALE_FACTOR (C_AQUARIUM_HEIGHT / C_REAL_AQUARIUM_HEIGHT)
#define C_AQUARIUM_WIDTH (126.0f * C_AQUARIUM_SCALE_FACTOR)
#define C_AQUARIUM_DEPTH (89.0f * C_AQUARIUM_SCALE_FACTOR)

#define C_PERSON_HEIGHT 1.5f

#define C_ROOM_SIZE 15.0f

#endif  // CONFIG_HPP
